apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-soc-api
  namespace: soc
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<account-id>:role/aws-soc-api-irsa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-soc-ingest-worker-s3-event
  namespace: soc
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<account-id>:role/aws-soc-ingest-s3-event-irsa
