apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-soc-api
  namespace: aws-soc
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<account-id>:role/aws-soc-api-irsa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-soc-ingest-worker
  namespace: aws-soc
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<account-id>:role/aws-soc-ingest-irsa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-soc-matcher-worker
  namespace: aws-soc
