apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-soc-ingest-worker-s3-event
  namespace: soc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-soc-ingest-worker-s3-event
  template:
    metadata:
      labels:
        app: aws-soc-ingest-worker-s3-event
    spec:
      serviceAccountName: aws-soc-ingest-worker-s3-event
      containers:
        - name: ingest-worker-s3-event
          image: doctor8181/aws-soc-platform-ingest-worker-s3-event:0.2.1-concurrent-worker-20260521-125628
          imagePullPolicy: IfNotPresent
          env:
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: aws-soc-config
                  key: AWS_REGION
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-soc-aws-creds
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-soc-aws-creds
                  key: AWS_SECRET_ACCESS_KEY
            - name: S3_OBJECT_CREATED_QUEUE_URL
              valueFrom:
                configMapKeyRef:
                  name: aws-soc-config
                  key: S3_OBJECT_CREATED_QUEUE_URL
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: aws-soc-secrets
                  key: DATABASE_URL
            - name: WORKER_NAME
              valueFrom:
                configMapKeyRef:
                  name: aws-soc-config
                  key: INGEST_S3_EVENT_WORKER_NAME
            - name: S3_EVENT_SQS_MAX_MESSAGES
              valueFrom:
                configMapKeyRef:
                  name: aws-soc-config
                  key: S3_EVENT_SQS_MAX_MESSAGES
            - name: S3_EVENT_SQS_WAIT_SECONDS
              valueFrom:
                configMapKeyRef:
                  name: aws-soc-config
                  key: S3_EVENT_SQS_WAIT_SECONDS
            - name: S3_EVENT_SQS_VISIBILITY_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: aws-soc-config
                  key: S3_EVENT_SQS_VISIBILITY_TIMEOUT
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
